apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: demo-apps
  labels:
    app: mysql
    tier: database
    environment: ${environment}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${mysql_storage_class}
  resources:
    requests:
      storage: ${mysql_storage_size}