AWSTemplateFormatVersion: '2010-09-09'
Description: 'Target Role for Terraform Deployments with Service-Level Permissions'

Parameters:
  TerraformStateBucketName:
    Type: String
    Description: 'Nombre del bucket de S3 donde guardas el tfstate'

Resources:
  TerraformDeployRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/github-roles/'
      RoleName: 'TerraformDeployRole'
      Description: 'Rol específico para ejecutar Terraform desde GitHub Actions'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !ImportValue GitHubBootstrapRoleArn
            Action:
              - sts:AssumeRole
              - sts:TagSession
      
      Policies:
        # 1. Acceso al Backend de S3
        - PolicyName: TerraformBackendAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub 'arn:aws:s3:::${TerraformStateBucketName}'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub 'arn:aws:s3:::${TerraformStateBucketName}/*'

        # 2. Servicios administrados por Terraform en este proyecto
        - PolicyName: TerraformServicesAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*
                  - iam:*
                  - ssm:*
                Resource: '*'

Outputs:
  RoleArn:
    Description: 'ARN del rol para usar en la configuracion de Terraform'
    Value: !GetAtt TerraformDeployRole.Arn